# Имя workflow
name: Node.js CI (Windows)

# Когда запускать workflow
on:
  push:
    branches: [ main ]       # запуск при пуше в main
  pull_request:
    branches: [ main ]       # запуск при создании PR в main
  workflow_dispatch:         # ручной запуск через интерфейс GitHub
  # Другие варианты `on`:
  # schedule:        # запуск по расписанию (cron)
  # release:         # запуск при создании релиза
  # issue_comment:   # запуск при комментарии к issue

jobs:
  build:
    # На какой ОС запускать
    runs-on: windows-latest  # Используем Windows для сборки
    # Варианты: ubuntu-latest, ubuntu-22.04, windows-latest, windows-2022, macos-latest

    steps:
      # Шаг 1: Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Устанавливаем зависимости
      - name: Install dependencies
        run: npm install

      # Шаг 3: Запускаем тесты
      - name: Run tests
        run: npm test

      # Шаг 4: Покрытие тестами
      - name: Check coverage
        run: npm run coverage
